CREATE TABLE USER(
    ID INT(20) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(45) DEFAULT NULL,
    ADDRESS VARCHAR(20) DEFAULT NULL,
    AGE INT(20) DEFAULT NULL,
    GENDER VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (ID)
)