INSERT INTO USER(ID, NAME, ADDRESS, AGE, GENDER) VALUES(1001, 'Pavan', 'INDIA', 30, 'MALE');
INSERT INTO USER(ID, NAME, ADDRESS, AGE, GENDER) VALUES(1002, 'Pavan C', 'INDIA', 25, 'MALE');
INSERT INTO USER(ID, NAME, ADDRESS, AGE, GENDER) VALUES(1003, 'Pavan N', 'INDIA', 25, 'MALE');