CREATE TABLE BOOK(
    ID INT(20) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(45) DEFAULT NULL,
    CATEGORY VARCHAR(20) DEFAULT NULL,
    AUTHOR VARCHAR(45) DEFAULT NULL,
    PUBLISHER VARCHAR(45) DEFAULT NULL,
    PRIMARY KEY (ID)
)