INSERT INTO BOOK(ID, NAME, CATEGORY, AUTHOR, PUBLISHER) VALUES(1001, 'JPOP 1', 'JAVA TRAINING', 'PAVAN1', 'PAVAN1');
INSERT INTO BOOK(ID, NAME, CATEGORY, AUTHOR, PUBLISHER) VALUES(1002, 'JPOP 2', 'JAVA TRAINING', 'PAVAN2', 'PAVAN2');
INSERT INTO BOOK(ID, NAME, CATEGORY, AUTHOR, PUBLISHER) VALUES(1003, 'JPOP 3', 'JAVA TRAINING', 'PAVAN3', 'PAVAN3');
INSERT INTO BOOK(ID, NAME, CATEGORY, AUTHOR, PUBLISHER) VALUES(1004, 'JPOP 4', 'JAVA TRAINING', 'PAVAN4', 'PAVAN4');